// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt52o3vCm3EFZ52hUtbemkYxy9ORhjc30',
    appId: '1:646137391676:web:356c6f02fe95cb0792f139',
    messagingSenderId: '646137391676',
    projectId: 'errand-buddy-dfc87',
    authDomain: 'errand-buddy-dfc87.firebaseapp.com',
    storageBucket: 'errand-buddy-dfc87.firebasestorage.app',
    measurementId: 'G-166ENTLWSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9TLQUrKdyLOarN5zn3tA74i4U6tMImfM',
    appId: '1:646137391676:android:0df0a7a369a529b292f139',
    messagingSenderId: '646137391676',
    projectId: 'errand-buddy-dfc87',
    storageBucket: 'errand-buddy-dfc87.firebasestorage.app',
  );
}
